/*
 * github webhook receiver
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ReleaseRelease struct {
	Name string `json:"name"`

	TagName string `json:"tag_name"`
}
