/*
 * github webhook receiver
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// github release event
type Release struct {
	Action string `json:"action"`

	Release *ReleaseRelease `json:"release"`

	Repository *ReleaseRepository `json:"repository"`
}
